sudo: false
dist: bionic
language: python
cache: pip
python:
  - "3.6"
addons:
  chrome: stable
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
env:
  global:
    - PGPORT=5433
    - KINGFISHER_PROCESS_DB_URI='postgres:///travis'
services:
  - postgresql
install:
  - "pip install -r requirements_dev.txt"
script:
  - "flake8 ocdskingfisherprocess/ ocdskingfisher-process-cli tests setup.py"
  - "KINGFISHER_PROCESS_WEB_API_KEYS=1234 pytest --cov ocdskingfisherprocess"
after_success:
  coveralls
