sudo: false
dist: bionic
language: python
cache: pip
python:
  - "3.6"
addons:
  chrome: stable
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
env:
  global:
    - KINGFISHER_PROCESS_DB_URI='postgres:///travis'
    - KINGFISHER_PROCESS_WEB_API_KEYS=1234
install:
  - pip install -r requirements_dev.txt
script:
  - flake8 ocdskingfisherprocess tests ocdskingfisher-process-cli setup.py
  - pytest --cov ocdskingfisherprocess
after_success:
  coveralls
